DROP PROCEDURE IF EXISTS INSERTAR_BIBLIOTECA;
DROP PROCEDURE IF EXISTS MODIFICAR_BIBLIOTECA;
DROP PROCEDURE IF EXISTS ELIMINAR_BIBLIOTECA;
DROP PROCEDURE IF EXISTS OBTENER_BIBLIOTECA_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_BIBLIOTECAS_TODAS;

DROP PROCEDURE IF EXISTS INSERTAR_ARTICULO;
DROP PROCEDURE IF EXISTS MODIFICAR_ARTICULO;
DROP PROCEDURE IF EXISTS ELIMINAR_ARTICULO;
DROP PROCEDURE IF EXISTS OBTENER_ARTICULO_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_ARTICULOS_TODOS;
DROP PROCEDURE IF EXISTS INSERTAR_LIBRO;
DROP PROCEDURE IF EXISTS MODIFICAR_LIBRO;
DROP PROCEDURE IF EXISTS ELIMINAR_LIBRO;
DROP PROCEDURE IF EXISTS OBTENER_LIBRO_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_LIBROS_TODOS;
DROP PROCEDURE IF EXISTS INSERTAR_TESIS;
DROP PROCEDURE IF EXISTS MODIFICAR_TESIS;
DROP PROCEDURE IF EXISTS ELIMINAR_TESIS;
DROP PROCEDURE IF EXISTS OBTENER_TESIS_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_TESIS_TODOS;

DROP PROCEDURE IF EXISTS INSERTAR_ROL;
DROP PROCEDURE IF EXISTS MODIFICAR_ROL;
DROP PROCEDURE IF EXISTS ELIMINAR_ROL;
DROP PROCEDURE IF EXISTS OBTENER_ROL_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_ROLES_TODOS;

DROP PROCEDURE IF EXISTS INSERTAR_USUARIO;
DROP PROCEDURE IF EXISTS MODIFICAR_USUARIO;
DROP PROCEDURE IF EXISTS ELIMINAR_USUARIO;
DROP PROCEDURE IF EXISTS OBTENER_USUARIO_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_USUARIOS_TODOS;

DROP PROCEDURE IF EXISTS INSERTAR_CONTRIBUYENTE;
DROP PROCEDURE IF EXISTS MODIFICAR_CONTRIBUYENTE;
DROP PROCEDURE IF EXISTS OBTENER_CONTRIBUYENTE_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_CONTRIBUYENTES_TODOS;
DROP PROCEDURE IF EXISTS ASIGNAR_CONTRIBUYENTE;
DROP PROCEDURE IF EXISTS LISTAR_AUTORES_POR_MATERIAL;
DROP PROCEDURE IF EXISTS LISTAR_CONTRIBUYENTES_POR_MATERIAL;

DROP PROCEDURE IF EXISTS INSERTAR_EDITORIAL;
DROP PROCEDURE IF EXISTS MODIFICAR_EDITORIAL;
DROP PROCEDURE IF EXISTS OBTENER_EDITORIAL_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_EDITORIALES_TODAS;
DROP PROCEDURE IF EXISTS ASIGNAR_EDITORIAL;

DROP PROCEDURE IF EXISTS INSERTAR_EJEMPLAR;
DROP PROCEDURE IF EXISTS MODIFICAR_EJEMPLAR;
DROP PROCEDURE IF EXISTS ELIMINAR_EJEMPLAR;
DROP PROCEDURE IF EXISTS OBTENER_EJEMPLAR_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_EJEMPLARES_TODOS;

DROP PROCEDURE IF EXISTS INSERTAR_PRESTAMO;
DROP PROCEDURE IF EXISTS MODIFICAR_PRESTAMO;
DROP PROCEDURE IF EXISTS OBTENER_PRESTAMO_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_PRESTAMOS_TODOS;


DROP PROCEDURE IF EXISTS INSERTAR_SANCION;
DROP PROCEDURE IF EXISTS MODIFICAR_SANCION;
DROP PROCEDURE IF EXISTS FINALIZAR_SANCION;
DROP PROCEDURE IF EXISTS OBTENER_SANCION_X_ID;
DROP PROCEDURE IF EXISTS LISTAR_SANCIONES_TODAS;

